### PR TITLE
Show better error message Trello API returns an error

### PR DESCRIPTION
**Pull request by sogamoso**
Before this change `MultiJson::ParseError` was raised because currently Trello
API doesn't respons with a JSON body in that case.

The intention is to check if the response was not successful and return that error message to the user via the CLI instead of raising a confusing JSON parse exception.

### CODE REVIEW

**Comment by balvig** [comment]
@sebasoga could you try pushing an empty commit? For some reason CI didn't pick it up... 😢 
I'm also not able to push directly to your branch 😢  😢

**Comment by sogamoso** [comment]
@balvig can you try again? I disabled and enabled access to my branch, hopefully it will work now.

**Comment by balvig** [comment]
@sebasoga success! Thanks so much for this 🙏  
Made a couple of last (personal preference-ish) tweaks. Will release a new version after merge 👍

**Comment by sogamoso** [comment]
I wonder, why are those requests to Rubygems being done?

**Comment by balvig** [comment]
@sebasoga 

https://github.com/balvig/trello_flow/blob/master/lib/trello_flow/main.rb#L13 and https://github.com/balvig/trello_flow/blob/master/lib/trello_flow/version.rb#L14-L16 😉

**Comment by sogamoso** [comment]
@balvig thanks for links!

**Pull request merged**
