### PR TITLE
Fix cleanup branches

### PR DESCRIPTION
**Pull request by lazlyhu**
I using the cleanup commend really lot, but at the last time it left too many already merged branch in my localhost. This PR aim to fix this issue

### CODE REVIEW

**Comment by balvig** [comment]
Aha! I've actually stopped using `cleanup` because it didn't work well for me either, great to get it fixed! 

Could you I trouble you to quickly explain what this change does in practice, ie how does it change the behavior from before? 🙇

**Comment by lazlyhu** [comment]
@balvig Thank you 😄 

## About `git` parameter

`-D` forcing the branch delete, and It can be dangerous sometimes, so I soft it back to `-d` which delete only the merged branches in origin.

## About `grep` parameter

And about the `grep` change, if I have 4 branches, for example these
```
apple
master
l.growing_an_apple
l.growing_an_peach.master.1234abcd
```
All (except the `master`) are merged in the origin we except remove all.
But with the old grep we got this list, because the `.master.` filtering (if the `master` is the target):
```
l.growing_an_peach.master.1234abcd
```
With the grep in this commit we got, because get all merged, and drop the target (in this case the master):
```
apple
l.growing_an_apple
l.growing_an_peach.master.1234abcd
```

**Comment by balvig** [comment]
@lazlyhu aaah I see now, yeh that part was actually originally intentional! 😅 

The problem was that someone might make an empty release branch (ie no commits yet) and then running this script would get rid of it.

Come to think of it though that sounds like a bit of an edge case and I would like to clean up my branches too, so let me give this another look, I suppose we can drop the filter entirely.

**Comment by balvig** [comment]
After having taken a look at other solutions found on GitHub, you may not like my conclusion 😅 , but I actually think I prefer taking `cleanup` out of `cp8_cli`!

Main reasons being:

- It's not really something that's unique to our workflow
- There are better solutions now, offering for example previews of what is to be deleted etc

The one I have chosen for the time being is: https://github.com/Seinh/git-prune

Running 

```
gprune -b
```

gives me similar behavior to what `cp8_cli` does, with some extra niceness to it!

**Pull request closed without merging**
